apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: mongo-db
      image: mongo:4.4
      command: ["mongod", "--bind_ip_all"]
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: nfs-volume
          mountPath: "/data/db"

  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: my-pvc
