apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  port: "3000"
  




# ---- secret.yml

# if there is any sensitive data we can use secret
# apiversion: apps/v1
# kind: secret
# metadata:
#   name: backend-config
# data:
#   database_url: "mongodb+srv://shreyash:


# --- with env variable
# apiVersion: v1
# kind: Secret
# metadata:
#   name: backend-config
# data:
#     env: "cG9ydD0zMDAwCg=="

